# basic options
title: The Cancer Genome Atlas - Kidney Clear Cell Carcinoma
description: Developed for ECE 4783 Introduction to Medical Image Processing (Georgia Institute of Technology)

author: Alexander Fache

social-network-links:
  email: alexander.fache@gmail.com
  github: alexanderfache6

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
