# basic options
title: The Cancer Genome Atlas (TCGA) - Kidney Clear Cell Carcinoma
author: Alexander Fache
#email: alexander.fache@gmail.com
description: Developed for ECE 4783 Introduction to Medical Image Processing
github_username: alexanderfache6

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
