# basic options
title: The Cancer Genome Atlas - Kidney Clear Cell Carcinoma
description: Developed for ECE 4783 Introduction to Medical Image Processing (Georgia Institute of Technology)

author: Alexander Fache
email: alexander.fache@gmail.com
github_username: alexanderfache6

github:
  is_project_page: false

baseurl: /TCGA-kidney

{{ site.baseurl }}/assignments/Module_3/Fache_Lovejoy_UG2_Final Presentation.pdf

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
