title: The Cancer Genome Atlas - Kidney Clear Cell Carcinoma
description: Developed for ECE 4783 Medical Image Processing (Georgia Institute of Technology)

# author: Alexander Fache
# github_username: alexanderfache6

github:
  is_project_page: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
